# Generated by Django 5.0.14 on 2026-09-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('P', 'Prestado'), ('R', 'Reservado'), ('DA', 'Dañado'), ('PE', 'Perdido')], default='D', max_length=2)),
            ],
        ),
    ]
