# Generated by Django 5.0.14 on 2026-09-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
