# Generated by Django 5.0.14 on 2026-09-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosapp', '0002_alter_libro_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='codigo',
        ),
    ]
